name: bertopic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - hdbscan
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - umap-learn
  - matplotlib
  - plotly
  - rapidsai::cuml
